### PR TITLE
ft-187570826 Admin Dashboard Feature

### PR DESCRIPTION
**Pull request by kirengamartial**
### What does this PR do?

This PR implements functionality for the Admin to view all accounts and manage user roles and permissions within the application.

### Description of Task to be completed?

- Create an interface for Super Administrators to view a list of all user accounts
- Implement role assignment functionality, allowing Super Administrators to set roles (IT Staff, Seller, Buyer) for any staff member using their email address
- Ensure proper access control based on assigned roles

### What are the relevant pivotal tracker stories
https://www.pivotaltracker.com/n/projects/2703469

### CODE REVIEW

**Review by robsdagreat — APPROVED** [review]
Well done @kirengamartial , we're good to go for sure!

**Review by Ishimwe7 — APPROVED** [review]
Well done @kirengamartial , good job

**Review by Balinda21 — APPROVED** [review]
Well designed and well integrated,
 nice work @kirengamartial

**Review by bahati10 — APPROVED** [review]
Good job on this. The Dashboard looks fabulous

**Pull request merged**
