### PR TITLE
ft seller should be able to delete a product

### PR DESCRIPTION
**Pull request by derrick-nuby**
### What does this PR do?

This PR adds functionality of deletion of a product, by a seller.

### Description of Task to be completed?

Seller should be able to delete only products he/she owns

### How should this be manually tested?

go to `/seller/products` or `/seller/product/{productID}` and delete a product

### What are the relevant pivotal tracker stories
`#187570824`

### CODE REVIEW

**Review by Balinda21 — APPROVED** [review]

**Review by kirengamartial — APPROVED** [review]
Good @Derrick-Nuby and this PR is ready for review

**Review by Ishimwe7 — APPROVED** [review]
Well done Derrick

**Review by robsdagreat — COMMENTED** [review]
Why are there some product details on singleSellerProductPage not displaying ?

**Review by Balinda21 — APPROVED** [review]
Great work

**Review by DeliceLydia — APPROVED** [review]

**Pull request merged**
