### PR TITLE
ft(seller-checkout): Have a seller be able to checkout

### PR DESCRIPTION
**Pull request by robsdagreat**
What does this PR do?

Have a seller be able to checkout.

Description of Task to be completed?

As a seller, you're allowed to add products to cart which are not yours and be able to checkout and proceed to payment.

How should this be manually tested?

N/A

Any background context you want to provide?

N/A

Screenshots (if appropriate)

 N/A

 Questions:

 N/A

What are the relevant pivotal tracker stories

#187987300

### CODE REVIEW

**Review by Balinda21 — APPROVED** [review]
The codes look good and the PR is ready for merge

**Review by rodriguecyber — APPROVED** [review]

**Review by kirengamartial — APPROVED** [review]
Good job @robsdagreat and this is ready for merge

**Review by Ishimwe7 — APPROVED** [review]
great work @robsdagreat , well done

**Review by derrick-nuby — COMMENTED** [review]
Everything works as expected; This PR is ready for merge

**Pull request merged**
