### PR TITLE
ft Requesting a reset password due to a forgotten password front-end

### PR DESCRIPTION
**Pull request by derrick-nuby**
### What does this PR do?
Adds the frontend for password reset and verification through email,and integrting with the backend
### Description of Task to be completed?
* Implement forgotPassword page to send the email to the backend.
* Implement resetPassword method to verify the token and update the user's password.
* show and display various errors based on the backend.
### How should this be manually tested?
* Send a request to /forgot with email in the form.
* Check the received email for a password reset link.
* input a new password if the user already exists.

### What are the relevant pivotal tracker stories

#187570818

### CODE REVIEW

**Review by rodriguecyber — APPROVED** [review]

**Review by Balinda21 — CHANGES_REQUESTED** [review]
Solve conflicts

**Comment by derrick-nuby** [comment]
> Solve conflicts

All merge conflicts are fixed now

**Review by Balinda21 — APPROVED** [review]
Great

**Review by kirengamartial — APPROVED** [review]
good it is ready for merge

**Pull request merged**
