### PR TITLE
Seller can add a new product

### PR DESCRIPTION
**Pull request by bahati10**
### What does this PR do?
* Implements the functionality for sellers to create new products on their dashboard.
* Includes necessary fields for product information, such as name, description, price, quantity, images, and categories.
* Handles product image, validation, and storage.
* Provides user feedback through success/error messages.

### Description of Task Completed
* Developed a product creation form with appropriate input fields.
* Integrated image upload functionality with necessary validations and error handling.
* Added success/error messages to provide user feedback.
* Tested the feature thoroughly to ensure correct product creation and data persistence.

### How should this be manually tested?
1. Log in as a seller.
2. Navigate to the product creation page.
3. Fill in all required product details (name, description, price, quantity, images, category).
4. Submit the product creation form.
5. Verify that the product is successfully created and displayed on the seller's product list.
6. Test with invalid data to ensure proper error handling.7. Test the product creation process with different product types and categories.

### What does this PR do?
* Implements the functionality for sellers to create new products on their dashboard.
* Includes necessary fields for product information, such as name, description, price, quantity, images, and categories.
* Handles product image uploads, validation, and storage.
* Provides user feedback through success/error messages.

### Description of Task Completed
* Developed a product creation form with appropriate input fields.
* Implemented backend logic to handle product data submission and storage.
* Integrated image upload functionality with necessary validations and error handling.
* Added success/error messages to provide user feedback.
* Tested the feature thoroughly to ensure correct product creation and data persistence.

### How should this be manually tested?
1. Log in as a seller.
2. Navigate to the product creation page.
3. Fill in all required product details (name, description, price, quantity, images, category).
4. Submit the product creation form.
5. Verify that the product is successfully created and displayed on the seller's product list.
6. Test with invalid data to ensure proper error handling.
7. Check image upload functionality and validation.
8. Test the product creation process with different product types and categories.

### Any background context you want to provide?
* This PR is based on the following design specifications/mockups: [link to design assets]
* Related to pivotal tracker story [story ID]

### Screenshots (if appropriate)
[Include screenshots of the product creation form, success/error messages, and product listing]

### Questions:
* Are there any specific requirements for image formats or sizes?
* How should product categories be handled (dropdown, tags, etc.)?
* What is the desired behavior for duplicate product names or SKUs?

### What does this PR do?
* Implements the functionality for sellers to create new products on their dashboard.
* Includes necessary fields for product information, such as name, description, price, quantity, images, and categories.
* Handles product image uploads, validation, and storage.
* Provides user feedback through success/error messages.

### Description of Task Completed
* Developed a product creation form with appropriate input fields.
* Implemented backend logic to handle product data submission and storage.
* Integrated image upload functionality with necessary validations and error handling.
* Added success/error messages to provide user feedback.
* Tested the feature thoroughly to ensure correct product creation and data persistence.

### How should this be manually tested?
1. Log in as a seller.
2. Navigate to the product creation page.
3. Fill in all required product details (name, description, price, quantity, images, category).
4. Submit the product creation form.
5. Verify that the product is successfully created and displayed on the seller's product list.
6. Test with invalid data to ensure proper error handling.
7. Check image upload functionality and validation.
8. Test the product creation process with different product types and categories.

### Any background context you want to provide?
* This PR is based on the following design specifications/mockups: [link to design assets]
* Related to pivotal tracker story [story ID]

### Screenshots (if appropriate)
[Include screenshots of the product creation form, success/error messages, and product listing]

### Questions:
* Are there any specific requirements for image formats or sizes?
* How should product categories be handled (dropdown, tags, etc.)?
* What is the desired behavior for duplicate product names or SKUs?

### What are the relevant pivotal tracker stories
#187570822

### CODE REVIEW

**Review by kirengamartial — APPROVED** [review]
good job @bahati10 and this pr is ready for merge

**Review by Balinda21 — APPROVED** [review]
Nicely done. The PR is ready to be merged.

**Review by Ishimwe7 — APPROVED** [review]
Well done, @bahati10 , we're ready to go

**Review by robsdagreat — APPROVED** [review]
Well done @bahati10 !

**Pull request merged**
