### PR TITLE
Fit-seller2faAuth

### PR DESCRIPTION
**Pull request by Balinda21**
### What does this PR do?
Seller Login after entering 2fa code

### CODE REVIEW

**Review by kirengamartial — APPROVED** [review]
good morris these changes are necessary and it is ready for merge

**Review by Ishimwe7 — APPROVED** [review]
Good job @Balinda21

**Review by DeliceLydia — COMMENTED** [review]
- [ ] I am getting this error when I click login
Screenshot 2024-07-05 at 13 47 37

**Comment by Balinda21** [comment]
> * [ ]  I am getting this error when I click login
> 
> Screenshot 2024-07-05 at 13 47 37

all good now

**Review by DeliceLydia — APPROVED** [review]

**Pull request merged**
