### PR TITLE
seller/buyer notification

### PR DESCRIPTION
**Pull request by kirengamartial**
### What does this PR do?
This PR implements the notification system for the application, ensuring users are notified of important events and actions related to products.

### Description of Task to be completed?

- Implement a notification system to alert users of important events/actions (product added, product expired, product bought, product discounted, etc.)
- Display a notification icon showing the number of new and unread notifications.
- Allow users to view all available notifications.
- Ensure notifications are sent to the correct user (seller or buyer).

### What are the relevant pivotal tracker stories
https://www.pivotaltracker.com/n/projects/2703469

### CODE REVIEW

**Review by robsdagreat — APPROVED** [review]
Well done @kirengamartial , this looks good!

**Review by Balinda21 — APPROVED** [review]
Great work @kirengamartial

**Review by Ishimwe7 — APPROVED** [review]
Well done @kirengamartial

**Review by derrick-nuby — APPROVED** [review]
You have implemented the feature correctly; and this PR is ready for merge.

**Review by bahati10 — APPROVED** [review]
Well implemented Martial

**Review by rodriguecyber — APPROVED** [review]

**Pull request merged**
