### PR TITLE
ft: Add 404 not found page

### PR DESCRIPTION
**Pull request by kirengamartial**
### What does this PR do?
This Pull Request adds a 404 not found page when you to try access the route that our application does not have

### CODE REVIEW

**Review by Balinda21 — APPROVED** [review]
That is helpful @kirengamartial,
 Great work!

**Review by robsdagreat — APPROVED** [review]
This is thoughtfully @kirengamartial well done.

**Review by Ishimwe7 — APPROVED** [review]
Good job @kirengamartial this was needed.

**Review by derrick-nuby — APPROVED** [review]
Changes are good and ready for mere

**Pull request merged**
